### ISSUE TITLE
마켓컬리 헤터, 푸터 분리 

### ISSUE THREAD

**Issue by LeeMooho** [NC4Mini/NC4_mini_project-Temp-#2]
지우님이 공유한 파일을 기준으로 공유 예정 (가장 최신 버전이므로)

**Comment by Robbie-Kim** [comment]
현 시점 header, footer
[다운로드](http://naver.me/Fjc5f8SN) or Mybox -> 비트캠프 4기 프로젝트 -> resource

### 구분
- reset, fonts, style.css : 기본 적용 css (static\css 에 위치)
- intro.js : 기본 적용 javascript (static\js 에 위치)
- footer, header, config.html : fragment 에 위치
- layout.html : layouts에 위치
- index.html : 메인페이지
